### PR TITLE
Added IPv4 Address Anonymizer

### PR DESCRIPTION
**Pull request by thekevinbrown**
This adds an IP address anonymizer so that users can anonymize IP addresses in their dataset. It always replaces with 127.x.x.x IP addresses, which are localhost.

### CODE REVIEW

**Comment by realrolfje** [comment]
Hi Kevin, I have the builds working again thanks to the kind people at Travis CI who provided me with credits for this open source project. I also merged some other pull requests (mainly documentation). Can you merge the develop branch into your pull request and push so that the build kicks off? Thanks!

**Comment by thekevinbrown** [comment]
Hey @realrolfje, as far as I can tell, upstream develop is already merged in this branch. I'm not sure how to kick the tests off again, but suspect you can trigger a build manually in Travis.

**Comment by thekevinbrown** [comment]
Hey @realrolfje, anything I can do here to help?

**Comment by realrolfje** [comment]
I have no idea why Travis doesn't pick up this PR, I'll have a look.

**Comment by realrolfje** [comment]
I had a look at travis-ci.com and my open source credits were not applied. Travis seems to have been problematic for me the past years (with the move to travis-ci.com, changing of webhooks, and now removal of balance). Maybe I should move to a different continuous build solution which integrates nicely with github. Any suggestions?

**Review by realrolfje — APPROVED** [review]

**Comment by thekevinbrown** [comment]
We use GitHub Actions, and while it’s been having downtime recently there is no tool that’s better integrated into GitHub.

**Pull request merged**
